# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  mysql:
       container_name: mysql-development-4
       image: mysql:5.7
       environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: medication
       ports:
       - 3309:3309
  #App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      context: spring-boot-demo # Use an image built from the specified dockerfile in the `spring-boot-demo` directory.
      dockerfile: docker-file
    ports:
        #"HOST:CONTAINTER"
      - "8083:8083" # Forward the exposed port 8080 on the container to port 8080 on the hostmachine
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/medication?autoReconnect=true&useSSL=false
    depends_on: 
      - mysql # This service depends on mysql. Start that first.

